version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./.infrastructure/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php-fpm:
    build:
      context: .
      dockerfile: ./.infrastructure/docker/php-fpm/Dockerfile
    volumes:
      - ./:/app

  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - ./.infrastructure/docker/postgres/dev-volume:/var/lib/postgresql/data/

